### PR TITLE
Added rvsteel_mtimer to the SoC + Example

### PR DESCRIPTION
**Pull request by AlexxMarkov**
To quickly check, change the makefile in SoC sim:
```
FIRMWARE   = $(RVSTEEL_ROOT)/demos/examples/mtimer/software/build/mtimer.hex
RUN_CMD +=--cycles=1000000 --host-out=0x80000000
```

### CODE REVIEW

**Comment by AlexxMarkov** [comment]
I have an idea to write cmake for build and change some things, I'll try to do that next time.

**Comment by AlexxMarkov** [comment]
I thought a little more, it seems I was wrong when I suggested separating boards and examples :(
Perhaps I will be wrong again, but maybe we need to combine them?

For example like this (in demos):

```
arty_a7_hello_world/
arty_a7_mtimer/
arty_a7_gpio/
cmod_a7_hello_world/
soc_sim_mtimer/
```

**Review by rafaelcalcada — APPROVED** [review]
Let's do these changes in the directory structure for another housekeeping pull request. I'll open another one this week. ;)

**Comment by AlexxMarkov** [comment]
Ok. I can offer one more option, but I’m not sure which is better)

```
demos
  +--hello_world
  |    +--arty_a7
  |    +--cmod_a7
  |    +--tang_nano_20k
  |    +--soc_sim
  |    +--software
  |
  +--mtimer
       +--soc_sim
       +--software
```

**Pull request merged**
