### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by rafaelcalcada**
Let's continue PR #27 here.

### CODE REVIEW

**Comment by AlexxMarkov** [comment]
Hello) May I suggest you use verilator as a linter? I usually try to listen to the linter's warnings, I think this makes the code cleaner.

**Review by AlexxMarkov — COMMENTED** [review]
I tried to build and run unit_tests, everything seems to be fine :)

**Comment by rafaelcalcada** [comment]
Sure, we can use Verilator for linting. ;)

**Review by AlexxMarkov — APPROVED** [review]
I think you can do a merge :)

**Comment by riscv-steel** [comment]
There was a config requiring the commits to be signed, which blocked (even myself) of merging it. I just unset it ;)

**Pull request merged**
