### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by riscv-steel**
Hi @AlexxMarkov, I put all tests on the same folder, out of the ip/ folder. I removed my Verilator script and left yours, and updated the README accordingly. If you are ok with the changes you can approve the review and I believe (if I set everything correctly) you will be able to accept the pull request. ;)

### CODE REVIEW

**Comment by AlexxMarkov** [comment]
Good job :)
Write me some recommendations for adding new IP, such as what code style to follow. Can I split one IP into several? For example, make a folder `ip/new_ip` where there will be `new_ip.v, new_ip_rx.v, new_ip_tx.v`. How should I name the folder and tests for testing a specific `ip/new_ip/new_ip.v`. You can also write about how commits should be formatted in git. There could be something else.

**Comment by rafaelcalcada** [comment]
I think we can do like this:

- all IPs go in the ip/ folder
- tests for ip/someip.v go in tests/someip/

I just moved the tests for rvsteel_core.v to tests/core/. Also, I'm thinking about prefixing all IP names with rvsteel_, so the names don't clash with preexisting modules a user might have. For example, `ram` and `uart` are too generic names, one might have used this names for a module somewhere else. What do you think?

**Comment by rafaelcalcada** [comment]
And sure you can split an IP module. As coding standards, I follow several guidelines found here: https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md. I don't follow everything though. We could start a CONTRIBUTING.md file and write some generic guidelines for coding.

**Comment by AlexxMarkov** [comment]
Regarding prefixes, I have not yet encountered a name conflict. I usually connect to the project only what I use. I suppose it all depends on the build system and the variability of what we need at a particular moment. I think if we use prefixes it won’t be any worse. See also how it was done in `opentitan/hw/ip/`.

Great, then I’ll try to follow the recommendations you refer to.

**Comment by rafaelcalcada** [comment]
I turned these changes into a more general housekeeping, so I renamed the branch. I'm opening a new pull request with the renamed branch: housekeeping.

**Pull request closed without merging**
