### PR TITLE
Fix loading mem init files in the new format in the Core IP simulator

### PR DESCRIPTION
**Pull request by rafaelcalcada**
Hi @AlexxMarkov, the changes I introduced in the mem init file format could not be read by the Core IP simulator. I just fixed it. I think now everything works with the new format.

### CODE REVIEW

**Comment by AlexxMarkov** [comment]
Hi @rafaelcalcada, did you rebuild the tests in the `unit_tests` folder and try to run them? Or was it a slightly different experiment?)

Yes, I think this is a useful fix. By the way, do you think we should switch to a binary format for Core IP simulator?
Then it will be possible to remove the work with string. But then we will have to rebuild `programs, references` and rewrite code `verilator` into `unit_tests.py`.

I also found a few problems. There is no check out of range ram. That is, when the file is larger than ram itself and the offset specified in `@address` is out of range.

**Comment by rafaelcalcada** [comment]
I did not :( but I will. Rebuilding the test programs is a bit complicated, but I think it's time for me to do it again and put a README file inside the unit_tests folder explaining how that files are generated.

**Comment by AlexxMarkov** [comment]
We can take our time and leave only this functionality.  Next, I suggest you think about how we can test the Core IP more seriously, perhaps we should use instruction generator [riscv-dv](https://github.com/chipsalliance/riscv-dv)

**Review by AlexxMarkov — APPROVED** [review]
Looks like I fixed the problem I was talking about)

**Pull request merged**
